name: "actions-template-sync"
description: "Synchronises changes of the template repository"
author: "AndreasAugustin"
branding:
  icon: cloud
  color: green
inputs:
  github_token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
    default: ${{ github.token }}
  source_repo_path:
    description: "Repository path of the template"
    required: true
  upstream_branch:
    description: "The target branch"
  pr_branch_name_prefix:
    description: "[optional] the prefix of branches created by this action"
    default: "main"
  pr_title:
    description: "[optional] the title of PRs opened by this action"
    default: "upstream merge template repository"
  pr_body:
    description: "[optional] the body of PRs opened by this action"
  pr_labels:
    description: "[optional] comma separated list of pull request labels"
    default: "template_sync"
  pr_reviewers:
    description: "[optional] comma separated list of pull request reviewers"
  pr_commit_msg:
    description: "[optional] the commit message of the template merge"
    default: "chore(template): merge template changes :up:"
  hostname:
    description: "[optional] the hostname of the GitHub repository"
    default: "github.com"
  is_force_deletion:
    description: "[optional] set to true if you want to force delete files which are deleted within the source repository even if they contain changes"
    default: "true"
  git_user_name:
    description: "[optional] set the committer git user.name for the merge commit"
  git_user_email:
    description: "[optional] set the committer git user.email for the merge commit"
  steps:
    description: "[optional] set the steps to execute within the action"
  template_sync_ignore_file_path:
    description: "[optional] set the path to the ignore file"
    default: ".templatesyncignore"
outputs:
  pr_branch:
    description: "The name of the PR branch"
    value: main
runs:
  using: "composite"
  # image: "src/Dockerfile"
  steps:
    - name: github sync
      run: ${{github.action_path}}/src/entrypoint.sh
      # working-directory: src/
      shell: bash
      id: sync
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        SOURCE_REPO_PATH: ${{ inputs.source_repo_path }}
        UPSTREAM_BRANCH: ${{ inputs.upstream_branch }}
        PR_BRANCH_NAME_PREFIX: ${{ inputs.pr_branch_name_prefix }}
        PR_TITLE: ${{ inputs.pr_title }}
        PR_BODY: ${{ inputs.pr_body }}
        PR_LABELS: ${{ inputs.pr_labels }}
        PR_REVIEWERS: ${{ inputs.pr_reviewers }}
        PR_COMMIT_MSG: ${{ inputs.pr_commit_msg }}
        HOSTNAME: ${{ inputs.hostname }}
        IS_FORCE_DELETION: ${{ inputs.is_force_deletion }}
        GIT_USER_NAME: ${{ inputs.git_user_name }}
        GIT_USER_EMAIL: ${{ inputs.git_user_email }}
        STEPS: ${{ inputs.steps }}
        TEMPLATE_SYNC_IGNORE_FILE_PATH: ${{ inputs.template_sync_ignore_file_path }}
        IS_WITH_TAGS: ${{ inputs.is_with_tags }}
